config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'profiles/:id', to: 'users#show', as: :profile
  get 'profiles/:id/edit', to: 'users#edit', as: :edit_profile
  put 'profiles/:id', to: 'users#update'
  patch 'profiles/:id', to: 'users#update'

  resources :courses
  resources :locations
  resources :assignments do
    resources :submissions, only: [:index, :new, :create]
  end
  resources :submissions, only: [:show, :edit, :update, :destroy]

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :submissions
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  belongs_to :location
  belongs_to :course
  has_many :enrollments
  has_many :users, through: :enrollments

  def location_and_name
    "#{self.location.name} - #{self.course.name}"
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :cohorts
  has_many :locations, through: :cohorts
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :cohort
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :cohorts
  has_many :courses, through: :cohorts
  has_many :users
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :assignment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  # attach avatar with paperclip
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # enumerate roles
  extend Enumerize
  enumerize :role, in: [:student,:instructor,:director]
  # has one location
  belongs_to :location
  # has many enrollments
  has_many :enrollments
  has_many :cohorts, through: :enrollments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def index
    @assignments = Assignment.all
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      flash[:success] = 'Assignment was successfully created.'
      redirect_to assignments_path
    else
      flash[:danger] = 'There was a problem creating the Assignment.'
      render :new
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    if @assignment.update(assignment_params)
      flash[:success] = 'Assignment was successfully updated.'
      redirect_to assignment_path(@assignment)
    else
      flash[:danger] = 'There was a problem updating the Assignment.'
      render :edit
    end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    if @assignment.destroy
      flash[:success] = 'Assignment was successfully deleted.'
      redirect_to assignments_path
    else
      flash[:danger] = 'There was a problem deleting the Assignment'
      redirect_to assignments_path
    end
  end

  def assignment_params
    params.require(:assignment).permit(:title,
                                       :description,
                                       :content);
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @courses = Course.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      flash[:success] = 'Profile was successfully updated.'
      redirect_to profile_path(@user)
    else
      flash[:danger] = 'There was a problem updating your profile.'
      render :edit
    end
  end

  ##################################################
  private
  def profile_params
    params.require(:user).permit(:handle,
                                 :blurb,
                                 :avatar,
                                 :location_id,
                                 :cohort_ids => [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "modernizr/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar" data-topbar role="navigation" >
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">__TIYWERX__</a></h1>
        </li>
        <!-- The little menu that takes over when screen gets too small -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <!-- login section -->
        <ul class="right">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'logout', destroy_user_session_path, :method => :delete %>
            </li>
          <% else  %>
            <li>
              <%= link_to 'sign-in', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'register', new_user_registration_path %>
            </li>
          <% end %>
        </ul>
        <!-- main navigatoin section -->
        <ul class="left">
          <li>
            <%= link_to 'Courses', courses_path %>
          </li>
          <li>
            <%= link_to 'Locations', locations_path %>
          </li>
        </ul>
      </section>
    </nav>

    <% if notice %>
      <div data-alert class="alert-box success">
        <%= notice %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if alert %>
      <div data-alert class="alert-box alert">
        <%= alert %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
      
    <%= yield %>

  </body>
</html>